#pragma once

#include <errno.h>
#include <csignal>

#include <algorithm>
#include <array>
#include <atomic>
#include <cctype>
#include <chrono>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <exception>
#include <filesystem>
#include <fstream>
#include <functional>
#include <future>
#include <iomanip>
#include <iostream>
#include <map>
#include <memory>
#include <mutex>
#include <optional>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <thread>
#include <vector>

#include <nlohmann/json.hpp>

#include "auth/auth_http_service.h"
#include "auth/auth_payload_service.h"
#include "auth/auth_support_service.h"
#include "scheduler/assignment_orchestration_service.h"
#include "app/controller_language_support.h"
#include "app/controller_scheduler_service_builder.h"
#include "app/controller_scheduler_service_factory.h"
#include "bundle/bundle_cli_service.h"
#include "bundle/bundle_http_service.h"
#include "infra/controller_action.h"
#include "app/controller_cli.h"
#include "app/controller_command_line.h"
#include "app/controller_time_support.h"
#include "infra/controller_event_service.h"
#include "infra/controller_health_service.h"
#include "infra/controller_print_service.h"
#include "infra/controller_request_support.h"
#include "infra/controller_runtime_support_service.h"
#include "app/controller_service_interfaces.h"
#include "plane/controller_state_service.h"
#include "http/controller_http_server.h"
#include "http/controller_http_route_handler.h"
#include "http/controller_http_route_handlers.h"
#include "http/controller_http_router.h"
#include "plane/desired_state_policy_service.h"
#include "plane/dashboard_service.h"
#include "infra/controller_network_manager.h"
#include "http/controller_http_server_support.h"
#include "http/controller_http_transport.h"
#include "http/controller_http_types.h"
#include "host/hostd_http_service.h"
#include "interaction/interaction_http_service.h"
#include "knowledge/knowledge_vault_http_service.h"
#include "interaction/interaction_runtime_support_service.h"
#include "model/model_library_http_service.h"
#include "model/model_library_service.h"
#include "plane/plane_http_service.h"
#include "plane/plane_mutation_service.h"
#include "plane/plane_realization_service.h"
#include "plane/plane_registry_service.h"
#include "read_model/read_model_http_service.h"
#include "read_model/read_model_cli_service.h"
#include "read_model/read_model_service.h"
#include "app/remote_controller_cli_service.h"
#include "infra/controller_remote_client.h"
#include "infra/controller_ui_service.h"
#include "scheduler/scheduler_http_service.h"
#include "scheduler/scheduler_domain_service.h"
#include "scheduler/scheduler_cli_service.h"
#include "scheduler/scheduler_execution_support.h"
#include "scheduler/scheduler_view_service.h"
#include "skills/plane_skill_catalog_service.h"
#include "skills/plane_skill_runtime_sync_service.h"
#include "skills/skills_factory_http_service.h"
#include "skills/skills_factory_service.h"
#include "read_model/state_aggregate_loader.h"
#include "host/host_registry_service.h"
#include "interaction/interaction_service.h"
#include "plane/plane_service.h"
#include "scheduler/scheduler_service.h"
#include "web/web_ui_service.h"

#include "naim/planning/compose_renderer.h"
#include "naim/security/crypto_utils.h"
#include "naim/state/demo_state.h"
#include "naim/planning/execution_plan.h"
#include "naim/importing/import_bundle.h"
#include "naim/runtime/infer_runtime_config.h"
#include "naim/state/models.h"
#include "naim/planning/planner.h"
#include "naim/core/platform_compat.h"
#include "naim/planning/reconcile.h"
#include "naim/runtime/runtime_status.h"
#include "naim/planning/scheduling_policy.h"
#include "naim/state/sqlite_store.h"
#include "naim/state/state_json.h"
